In [ ]:
import pandas as pd

In [ ]:
import nltk 
import numpy as np

In [ ]:
filename = 'spam.csv'
df = pd.read_csv(filename,encoding = 'latin-1')
print(df.shape)
print(df.columns)
print(df.head(2))

(5572, 5)
Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')
    v1                                                 v2 Unnamed: 2  \
0  ham  Go until jurong point, crazy.. Available only ...        NaN   
1  ham                      Ok lar... Joking wif u oni...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  


In [ ]:
data = df.values #numpy 
print(data.shape)
lines = data[:,1]# X
labels = data[:,0]# y
print(lines[:1])
print(labels[:1])

(5572, 5)
['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...']
['ham']


In [ ]:
# tách từ trong từng câu 
sentences = [nltk.word_tokenize(sent) for sent in lines]
print(sentences[0])
# lấy feature cho câu 

['Go', 'until', 'jurong', 'point', ',', 'crazy', '..', 'Available', 'only', 'in', 'bugis', 'n', 'great', 'world', 'la', 'e', 'buffet', '...', 'Cine', 'there', 'got', 'amore', 'wat', '...']


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer 

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
# kiểm tra từ điểm tạo trong tokenizer
#print(tokenizer.word_index)

/usr/local/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.9/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or 

In [ ]:
#texts_to_matrix(tokenizer, texts, mode = c("binary", "count", "tfidf", "freq"))
X = tokenizer.texts_to_matrix(sentences,mode='binary')
print(X)
print(X.shape)
print(len(X))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 1. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]]
(5572, 9444)
5572


In [ ]:
# chia tập train và tập test 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, labels, 
                                            test_size=0.2, random_state=0)
print(X_train.shape)
print(X_test.shape)

(4457, 9444)
(1115, 9444)


In [ ]:
from sklearn.naive_bayes import MultinomialNB 
from sklearn.metrics import classification_report

model_NB = MultinomialNB()#khai báo model 

model_NB = model_NB.fit(X_train,y_train) #learning 

y_pred = model_NB.predict(X_test) # test 

print(classification_report(y_test,y_pred)) #tính accuracy 

              precision    recall  f1-score   support

         ham       0.99      0.99      0.99       949
        spam       0.93      0.92      0.92       166

    accuracy                           0.98      1115
   macro avg       0.96      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
from sklearn import svm
model = svm.SVC(kernel="linear")

model = model.fit(X_train,y_train) #learning 

y_pred = model.predict(X_test) # test 

print(classification_report(y_test,y_pred)) #tính accuracy 

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       949
        spam       0.97      0.88      0.92       166

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
input_sent = 'Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005'
# dự đoán?
tokens = nltk.word_tokenize(input_sent)
print(tokens)
X_input = tokenizer.texts_to_matrix([tokens],mode='binary')
print(X_input)

['Free', 'entry', 'in', '2', 'a', 'wkly', 'comp', 'to', 'win', 'FA', 'Cup', 'final', 'tkts', '21st', 'May', '2005']
[[0. 0. 0. ... 0. 0. 0.]]


In [ ]:
y_pred = model_NB.predict(X_input)
print(y_pred)

['spam']


In [ ]:
from sklearn.linear_model import LogisticRegression  
model_LR = LogisticRegression()
model_LR = model_LR.fit(X_train,y_train)
y_pred = model_LR.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       949
        spam       0.99      0.89      0.94       166

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

